# [phases.setup]
# nixPkgs = ["python3", "gcc"]

# [phases.install]
# cmds = [
#     "python -m venv /opt/venv && . /opt/venv/bin/activate",
#     "pip install --no-cache-dir --upgrade pip",
#     # Paksa install torch versi CPU sebelum install yang lain
#     "pip install --no-cache-dir torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu",
#     "pip install --no-cache-dir -r backend/requirements.txt"
# ]

# [phases.build]
# cmds = []

# [start]
# cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"